### ISSUE TITLE
How to load the appender

### ISSUE THREAD

**Issue by shavo007** [manudwarf/log4js-protractor-appender#1]
`
{
  "appenders": [
    {
      "type": "log4js-protractor-appender"
    }
  ]
}
`

What file does this go in?

Thanks,
Shane.

**Comment by sagarm-optimus** [comment]
It think it should go into the Configure method of this logger. See below:

logger.configure({
  appenders: [
    {
      type: "log4js-protractor-appender",

    }
  ]

});

I am still working on this, but this is my understanding.

**Comment by valburyakov** [comment]
This works for me, after you declare `logger`, you can use it everywhere in your specs
```javascript
var log4js = require('log4js');
onPrepare: function() {
    log4js.configure({
      appenders: [
        { type: 'log4js-protractor-appender' }
      ]
    });
    global.logger = log4js.getLogger();
 }
```

**Comment by FrenchDilettante** [comment]
Sorry for not having replied earlier,

This plugin delegates to the console appender. We capture logs through Jenkins afterwards.
If you have knowledge of log4js, and want to update this plugin to be more generic and work with other appenders as well, we would welcome contributions.
Unfortunately, we do not plan to do so in the immediate future.
